export var STATES = ({ 
    trident: false,
    rudraksha: false,
    gem1: false,
    gem2: false,
    gem3: false,
    gem4: false,
    gem5: false,
    gem6: false,
    gem7: false,
    gem8: false,
    gem9: false,
    key1: false,
    key2: false,
    key3: false,
  });